-- Logs begin at Thu 2017-06-22 09:31:46 CST. --
Jun 22 09:51:12 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] Searching by: {'deleted': False, u'project_id': u'6e86902b80f944a88327cb5d02f365d8'} {{(pid=6318) get_all /opt/stack/nova/nova/compute/api.py:2485}}
Jun 22 09:51:12 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s {{(pid=6318) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:51:12 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s {{(pid=6318) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:51:12 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] Skipping already-collected cell0 list {{(pid=6318) _get_instances_by_filters_all_cells /opt/stack/nova/nova/compute/api.py:2677}}
Jun 22 09:51:12 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] Listing 1000 instances in cell aba39ac0-1435-47c1-8821-f2863b03ec65(cell1) {{(pid=6318) _get_instances_by_filters_all_cells /opt/stack/nova/nova/compute/api.py:2680}}
Jun 22 09:51:12 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s {{(pid=6318) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:51:12 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s {{(pid=6318) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:51:12 ubuntu nova-api[5615]: DEBUG nova.policy [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'da155bda1ee74d6c93908e2a37cc4cd4', 'roles': [u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'6e86902b80f944a88327cb5d02f365d8', 'project_domain_id': u'default'}: PolicyNotAuthorized: Policy doesn't allow os_compute_api:os-hide-server-addresses to be performed. {{(pid=6318) authorize /opt/stack/nova/nova/policy.py:168}}
Jun 22 09:51:12 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-f722e4c6-2c17-4dfe-bf1d-3ef488a13819 demo admin] 10.211.55.6 "GET /v2.1/servers/detail?all_tenants=True&project_id=6e86902b80f944a88327cb5d02f365d8 HTTP/1.1" status: 200 len: 2115 time: 0.4079700
Jun 22 09:51:30 ubuntu nova-api[5615]: DEBUG nova.osapi_compute.wsgi.server [None req-d3bf7ed7-d97e-4f42-ad11-d44e759058f1 demo admin] (6318) timed out ('10.211.55.6', 57380): timeout: timed out {{(pid=6318) process_request /usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py:739}}
Jun 22 09:51:42 ubuntu nova-api[5615]: DEBUG nova.osapi_compute.wsgi.server [None req-4ce9abff-bdf9-4846-9059-1625b956a877 None None] (6320) accepted ('10.211.55.6', 59456) {{(pid=6320) server /usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py:883}}
Jun 22 09:51:42 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-c8a04c70-b1a7-45fa-9182-b102e1b86c3f demo demo] 10.211.55.6 "GET /v2.1 HTTP/1.1" status: 302 len: 313 time: 0.0332820
Jun 22 09:51:42 ubuntu nova-api[5615]: DEBUG nova.api.openstack.wsgi [None req-8fba2afc-c3ee-43a6-9249-fc376b292b37 demo demo] Calling method '<bound method VersionsController.show of <nova.api.openstack.compute.versionsV21.VersionsController object at 0x7efc146c1750>>' {{(pid=6320) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:624}}
Jun 22 09:51:42 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-8fba2afc-c3ee-43a6-9249-fc376b292b37 demo demo] 10.211.55.6 "GET /v2.1/ HTTP/1.1" status: 200 len: 784 time: 0.0308962
Jun 22 09:51:42 ubuntu nova-api[5615]: DEBUG nova.api.openstack.wsgi [None req-f7a49f4b-eb69-4419-a5cd-ae27fd889605 demo demo] Calling method '<bound method ServersController.show of <nova.api.openstack.compute.servers.ServersController object at 0x7efc1412a990>>' {{(pid=6320) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:624}}
Jun 22 09:51:42 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-f7a49f4b-eb69-4419-a5cd-ae27fd889605 demo demo] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Fetching instance by UUID {{(pid=6320) get /opt/stack/nova/nova/compute/api.py:2453}}
Jun 22 09:51:42 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-f7a49f4b-eb69-4419-a5cd-ae27fd889605 demo demo] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:51:42 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-f7a49f4b-eb69-4419-a5cd-ae27fd889605 demo demo] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:51:42 ubuntu nova-api[5615]: DEBUG nova.policy [None req-f7a49f4b-eb69-4419-a5cd-ae27fd889605 demo demo] Policy check for os_compute_api:os-extended-server-attributes failed with credentials {'service_roles': [], 'user_id': u'7a282530f0c74dbfb711eba70ebf3ea4', 'roles': [u'anotherrole', u'Member'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': False, 'project_id': u'6e86902b80f944a88327cb5d02f365d8', 'project_domain_id': u'default'}: PolicyNotAuthorized: Policy doesn't allow os_compute_api:os-extended-server-attributes to be performed. {{(pid=6320) authorize /opt/stack/nova/nova/policy.py:168}}
Jun 22 09:51:42 ubuntu nova-api[5615]: DEBUG nova.policy [None req-f7a49f4b-eb69-4419-a5cd-ae27fd889605 demo demo] Policy check for os_compute_api:servers:show:host_status failed with credentials {'service_roles': [], 'user_id': u'7a282530f0c74dbfb711eba70ebf3ea4', 'roles': [u'anotherrole', u'Member'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': False, 'project_id': u'6e86902b80f944a88327cb5d02f365d8', 'project_domain_id': u'default'}: PolicyNotAuthorized: Policy doesn't allow os_compute_api:servers:show:host_status to be performed. {{(pid=6320) authorize /opt/stack/nova/nova/policy.py:168}}
Jun 22 09:51:43 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-f7a49f4b-eb69-4419-a5cd-ae27fd889605 demo demo] 10.211.55.6 "GET /v2.1/servers/cf049917-87e9-49e8-9dbd-9c1df24fe411 HTTP/1.1" status: 200 len: 1996 time: 0.3609490
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG nova.api.openstack.wsgi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Calling method '<bound method VolumeAttachmentController.delete of <nova.api.openstack.compute.volumes.VolumeAttachmentController object at 0x7efc14649210>>' {{(pid=6320) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:624}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Fetching instance by UUID {{(pid=6320) get /opt/stack/nova/nova/compute/api.py:2453}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.001s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] REQ: curl -g -i -X GET http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f -H "X-Service-Token: {SHA1}6349ac7419ee673e10b7cd665fb673dfb272ad86" -H "User-Agent: python-cinderclient" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}469434b122f1d4687e1ef4e22854afdff11e985b" {{(pid=6320) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] RESP: [200] X-Compute-Request-Id: req-81937ef0-c473-408f-8b83-fa18ef71100f Content-Type: application/json Content-Length: 1202 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-81937ef0-c473-408f-8b83-fa18ef71100f Date: Thu, 22 Jun 2017 01:51:43 GMT Connection: keep-alive
Jun 22 09:51:43 ubuntu nova-api[5615]: RESP BODY: {"volume": {"status": "in-use", "user_id": "7a282530f0c74dbfb711eba70ebf3ea4", "attachments": [{"server_id": "cf049917-87e9-49e8-9dbd-9c1df24fe411", "attachment_id": "53318d23-1f8c-4044-a958-05d2c29ac22a", "attached_at": "2017-06-22T01:51:04.000000", "host_name": null, "volume_id": "157e27cd-2edf-4ef0-accc-9b023620f26f", "device": "/dev/vdb", "id": "157e27cd-2edf-4ef0-accc-9b023620f26f"}], "links": [{"href": "http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f", "rel": "self"}, {"href": "http://10.211.55.6:8776/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f", "rel": "bookmark"}], "availability_zone": "nova", "bootable": "false", "encrypted": false, "created_at": "2017-06-20T06:48:14.000000", "description": null, "os-vol-tenant-attr:tenant_id": "6e86902b80f944a88327cb5d02f365d8", "updated_at": "2017-06-22T01:51:04.000000", "volume_type": "lvmdriver-1", "name": "cin04", "replication_status": null, "consistencygroup_id": null, "source_volid": null, "snapshot_id": null, "multiattach": false, "metadata": {"readonly": "False", "attached_mode": "rw"}, "id": "157e27cd-2edf-4ef0-accc-9b023620f26f", "size": 1}}
Jun 22 09:51:43 ubuntu nova-api[5615]:  {{(pid=6320) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] GET call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f used request id req-81937ef0-c473-408f-8b83-fa18ef71100f {{(pid=6320) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] REQ: curl -g -i -X POST http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action -H "X-Service-Token: {SHA1}6349ac7419ee673e10b7cd665fb673dfb272ad86" -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}469434b122f1d4687e1ef4e22854afdff11e985b" -d '{"os-begin_detaching": null}' {{(pid=6320) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-9d672d5e-056e-41f1-863e-aeb1f35ee811 Date: Thu, 22 Jun 2017 01:51:43 GMT Connection: keep-alive
Jun 22 09:51:43 ubuntu nova-api[5615]: RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
Jun 22 09:51:43 ubuntu nova-api[5615]:  {{(pid=6320) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:51:43 ubuntu nova-api[5615]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] POST call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action used request id req-9d672d5e-056e-41f1-863e-aeb1f35ee811 {{(pid=6320) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG nova.objects.instance [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Lazy-loading 'flavor' on Instance uuid cf049917-87e9-49e8-9dbd-9c1df24fe411 {{(pid=5698) obj_load_attr /opt/stack/nova/nova/objects/instance.py:1039}}
Jun 22 09:51:43 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] 10.211.55.6 "DELETE /v2.1/servers/cf049917-87e9-49e8-9dbd-9c1df24fe411/os-volume_attachments/157e27cd-2edf-4ef0-accc-9b023620f26f HTTP/1.1" status: 202 len: 405 time: 0.3358312
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG nova.notifications.objects.base [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object': OrphanedObjectError: Cannot call _load_projects on orphaned Flavor object {{(pid=5698) populate_schema /opt/stack/nova/nova/notifications/objects/base.py:125}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: INFO nova.compute.manager [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Detaching volume 157e27cd-2edf-4ef0-accc-9b023620f26f
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.utils [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] ==> get_connector_properties: call u"{'execute': None, 'my_ip': '10.211.55.6', 'enforce_multipath': True, 'host': 'ubuntu', 'root_helper': 'sudo nova-rootwrap /etc/nova/rootwrap.conf', 'multipath': False}" {{(pid=5698) trace_logging_wrapper /usr/local/lib/python2.7/dist-packages/os_brick/utils.py:146}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438337613488]: (3, 'os_brick.privileged.rootwrap.execute_root', ('cat', '/etc/iscsi/initiatorname.iscsi'), {}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): cat /etc/iscsi/initiatorname.iscsi {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "cat /etc/iscsi/initiatorname.iscsi" returned: 0 in 0.008s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438337613488]: (4, ('## DO NOT EDIT OR REMOVE THIS FILE!\n## If you remove this file, the iSCSI daemon will not start.\n## If you change the InitiatorName, existing access control lists\n## may reject this initiator.  The InitiatorName must be unique\n## for each iSCSI initiator.  Do NOT duplicate iSCSI InitiatorNames.\nInitiatorName=iqn.1993-08.org.debian:01:e46cdd201069\n', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.linuxfc [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] No Fibre Channel support detected on system. {{(pid=5698) get_fc_hbas /usr/local/lib/python2.7/dist-packages/os_brick/initiator/linuxfc.py:89}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.linuxfc [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] No Fibre Channel support detected on system. {{(pid=5698) get_fc_hbas /usr/local/lib/python2.7/dist-packages/os_brick/initiator/linuxfc.py:89}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.utils [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] <== get_connector_properties: return (15ms) {'initiator': u'iqn.1993-08.org.debian:01:e46cdd201069', 'ip': u'10.211.55.6', 'platform': u'x86_64', 'host': u'ubuntu', 'do_local_attach': False, 'os_type': u'linux2', 'multipath': False} {{(pid=5698) trace_logging_wrapper /usr/local/lib/python2.7/dist-packages/os_brick/utils.py:170}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: INFO nova.virt.block_device [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Attempting to driver detach volume 157e27cd-2edf-4ef0-accc-9b023620f26f from mountpoint /dev/vdb
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.guest [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Attempting initial detach for device vdb {{(pid=5698) detach_device_with_retry /opt/stack/nova/nova/virt/libvirt/guest.py:433}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.guest [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] detach device xml: <disk type="block" device="disk">
Jun 22 09:51:43 ubuntu nova-compute[5698]:   <driver name="qemu" type="raw" cache="none" io="native"/>
Jun 22 09:51:43 ubuntu nova-compute[5698]:   <source dev="/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1"/>
Jun 22 09:51:43 ubuntu nova-compute[5698]:   <target bus="virtio" dev="vdb"/>
Jun 22 09:51:43 ubuntu nova-compute[5698]:   <serial>157e27cd-2edf-4ef0-accc-9b023620f26f</serial>
Jun 22 09:51:43 ubuntu nova-compute[5698]:   <address type="pci"/>
Jun 22 09:51:43 ubuntu nova-compute[5698]: </disk>
Jun 22 09:51:43 ubuntu nova-compute[5698]:  {{(pid=5698) detach_device /opt/stack/nova/nova/virt/libvirt/guest.py:471}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.guest [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Successfully detached device vdb from guest. Persistent? 1. Live? True {{(pid=5698) _try_detach_device /opt/stack/nova/nova/virt/libvirt/guest.py:407}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.guest [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Start retrying detach until device vdb is gone. {{(pid=5698) detach_device_with_retry /opt/stack/nova/nova/virt/libvirt/guest.py:436}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.service.loopingcall [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Waiting for function nova.virt.libvirt.guest._do_wait_and_retry_detach to return. {{(pid=5698) func /usr/local/lib/python2.7/dist-packages/oslo_service/loopingcall.py:422}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.volume.iscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] calling os-brick to detach iSCSI Volume {{(pid=5698) disconnect_volume /opt/stack/nova/nova/virt/libvirt/volume/iscsi.py:72}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] ==> disconnect_volume: call u"{'args': (<os_brick.initiator.connectors.iscsi.ISCSIConnector object at 0x7fba61c7de90>, {u'device_path': u'/dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1', u'target_discovered': False, u'encrypted': False, u'qos_specs': None, u'target_iqn': u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', u'target_portal': u'10.211.55.6:3260', u'volume_id': u'157e27cd-2edf-4ef0-accc-9b023620f26f', u'auth_password': u'***', u'target_lun': 1, u'access_mode': u'rw', u'auth_username': u'o7mWUDheAUxfFJJJVB3g', u'auth_method': u'CHAP'}, None), 'kwargs': {}}" {{(pid=5698) trace_logging_wrapper /usr/local/lib/python2.7/dist-packages/os_brick/utils.py:146}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Lock "connect_volume" acquired by "os_brick.initiator.connectors.iscsi.disconnect_volume" :: waited 0.000s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.linuxscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Flushing IO for device /dev/sdc {{(pid=5698) flush_device_io /usr/local/lib/python2.7/dist-packages/os_brick/initiator/linuxscsi.py:145}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438337613488]: (3, 'os_brick.privileged.rootwrap.execute_root', ('blockdev', '--flushbufs', u'/dev/sdc'), {}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): blockdev --flushbufs /dev/sdc {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "blockdev --flushbufs /dev/sdc" returned: 0 in 0.003s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438337613488]: (4, ('', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.linuxscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Remove SCSI device /dev/sdc with /sys/block/sdc/device/delete {{(pid=5698) remove_scsi_device /usr/local/lib/python2.7/dist-packages/os_brick/initiator/linuxscsi.py:68}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438337613488]: (3, 'os_brick.privileged.rootwrap.execute_root', ('tee', '-a', u'/sys/block/sdc/device/delete'), {'process_input': '1'}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): tee -a /sys/block/sdc/device/delete {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "tee -a /sys/block/sdc/device/delete" returned: 0 in 0.039s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438337613488]: (4, ('1', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.linuxscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Checking to see if SCSI volume /dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1 has been removed. {{(pid=5698) wait_for_volume_removal /usr/local/lib/python2.7/dist-packages/os_brick/initiator/linuxscsi.py:76}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.linuxscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] SCSI volume /dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f-lun-1 has been removed. {{(pid=5698) wait_for_volume_removal /usr/local/lib/python2.7/dist-packages/os_brick/initiator/linuxscsi.py:82}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438337613488]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--op', 'update', '-n', 'node.startup', '-v', 'manual'), {'attempts': 1, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.startup -v manual {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op update -n node.startup -v manual" returned: 0 in 0.005s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438337613488]: (4, ('', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] iscsiadm ('--op', 'update', '-n', 'node.startup', '-v', 'manual'): stdout= stderr= {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438337613488]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--logout'), {'attempts': 1, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:51:43 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --logout {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --logout" returned: 0 in 0.516s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438337613488]: (4, ('Logging out of session [sid: 5, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260]\nLogout of [sid: 5, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260] successful.\n', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] iscsiadm ('--logout',): stdout=Logging out of session [sid: 5, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260]
Jun 22 09:51:44 ubuntu nova-compute[5698]: Logout of [sid: 5, target: iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f, portal: 10.211.55.6,3260] successful.
Jun 22 09:51:44 ubuntu nova-compute[5698]:  stderr= {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: request[140438337613488]: (3, 'os_brick.privileged.rootwrap.execute_root', ('iscsiadm', '-m', 'node', '-T', u'iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f', '-p', u'10.211.55.6:3260', '--op', 'delete'), {'attempts': 5, 'check_exit_code': (0, 21, 255), 'delay_on_retry': True}) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:443}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op delete {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:355}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.processutils [-] CMD "iscsiadm -m node -T iqn.2010-10.org.openstack:volume-157e27cd-2edf-4ef0-accc-9b023620f26f -p 10.211.55.6:3260 --op delete" returned: 0 in 0.009s {{(pid=6817) execute /usr/local/lib/python2.7/dist-packages/oslo_concurrency/processutils.py:385}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG oslo.privsep.daemon [-] privsep: reply[140438337613488]: (4, ('', '')) {{(pid=6817) loop /usr/local/lib/python2.7/dist-packages/oslo_privsep/daemon.py:456}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] iscsiadm ('--op', 'delete'): stdout= stderr= {{(pid=5698) _run_iscsiadm /usr/local/lib/python2.7/dist-packages/os_brick/initiator/connectors/iscsi.py:613}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Lock "connect_volume" released by "os_brick.initiator.connectors.iscsi.disconnect_volume" :: held 0.589s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG os_brick.initiator.connectors.iscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] <== disconnect_volume: return (589ms) None {{(pid=5698) trace_logging_wrapper /usr/local/lib/python2.7/dist-packages/os_brick/utils.py:170}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.volume.iscsi [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Disconnected iSCSI Volume vdb {{(pid=5698) disconnect_volume /opt/stack/nova/nova/virt/libvirt/volume/iscsi.py:78}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] REQ: curl -g -i -X POST http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}469434b122f1d4687e1ef4e22854afdff11e985b" -d '{"os-terminate_connection": {"connector": {"platform": "x86_64", "host": "ubuntu", "do_local_attach": false, "ip": "10.211.55.6", "os_type": "linux2", "multipath": false, "initiator": "iqn.1993-08.org.debian:01:e46cdd201069"}}}' {{(pid=5698) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-4265b4d3-d81b-4ed5-ba2d-e36fa05372a5 Date: Thu, 22 Jun 2017 01:51:44 GMT Connection: keep-alive
Jun 22 09:51:44 ubuntu nova-compute[5698]: RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
Jun 22 09:51:44 ubuntu nova-compute[5698]:  {{(pid=5698) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] POST call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action used request id req-4265b4d3-d81b-4ed5-ba2d-e36fa05372a5 {{(pid=5698) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:51:44 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] REQ: curl -g -i -X POST http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action -H "User-Agent: python-cinderclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}469434b122f1d4687e1ef4e22854afdff11e985b" -d '{"os-detach": {"attachment_id": "53318d23-1f8c-4044-a958-05d2c29ac22a"}}' {{(pid=5698) _http_log_request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:347}}
Jun 22 09:51:45 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] RESP: [202] Content-Type: text/html; charset=UTF-8 Content-Length: 0 Openstack-Api-Version: volume 3.0 Vary: OpenStack-API-Version X-Openstack-Request-Id: req-c56e131c-669f-4f65-9a4b-fecc6365413a Date: Thu, 22 Jun 2017 01:51:45 GMT Connection: keep-alive
Jun 22 09:51:45 ubuntu nova-compute[5698]: RESP BODY: Omitted, Content-Type is set to text/html; charset=UTF-8. Only application/json responses have their bodies logged.
Jun 22 09:51:45 ubuntu nova-compute[5698]:  {{(pid=5698) _http_log_response /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:395}}
Jun 22 09:51:45 ubuntu nova-compute[5698]: DEBUG cinderclient.v3.client [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] POST call to cinderv3 for http://10.211.55.6:8776/v3/6e86902b80f944a88327cb5d02f365d8/volumes/157e27cd-2edf-4ef0-accc-9b023620f26f/action used request id req-c56e131c-669f-4f65-9a4b-fecc6365413a {{(pid=5698) request /usr/local/lib/python2.7/dist-packages/keystoneauth1/session.py:640}}
Jun 22 09:51:45 ubuntu nova-compute[5698]: DEBUG nova.notifications.objects.base [None req-49f99b25-2fb2-41b2-ada1-0008b8fb47ce demo demo] Defaulting the value of the field 'projects' to None in FlavorPayload due to 'Cannot call _load_projects on orphaned Flavor object': OrphanedObjectError: Cannot call _load_projects on orphaned Flavor object {{(pid=5698) populate_schema /opt/stack/nova/nova/notifications/objects/base.py:125}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG nova.api.openstack.wsgi [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Calling method '<bound method ServersController.detail of <nova.api.openstack.compute.servers.ServersController object at 0x7efc141f6610>>' {{(pid=6320) _process_stack /opt/stack/nova/nova/api/openstack/wsgi.py:624}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Searching by: {'deleted': False, u'project_id': u'6e86902b80f944a88327cb5d02f365d8'} {{(pid=6320) get_all /opt/stack/nova/nova/compute/api.py:2485}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Lock "00000000-0000-0000-0000-000000000000" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Lock "00000000-0000-0000-0000-000000000000" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.002s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Skipping already-collected cell0 list {{(pid=6320) _get_instances_by_filters_all_cells /opt/stack/nova/nova/compute/api.py:2677}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG nova.compute.api [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Listing 1000 instances in cell aba39ac0-1435-47c1-8821-f2863b03ec65(cell1) {{(pid=6320) _get_instances_by_filters_all_cells /opt/stack/nova/nova/compute/api.py:2680}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" acquired by "nova.context.get_or_set_cached_cell_and_set_connections" :: waited 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG oslo_concurrency.lockutils [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Lock "aba39ac0-1435-47c1-8821-f2863b03ec65" released by "nova.context.get_or_set_cached_cell_and_set_connections" :: held 0.000s {{(pid=6320) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:51:48 ubuntu nova-api[5615]: DEBUG nova.policy [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] Policy check for os_compute_api:os-hide-server-addresses failed with credentials {'service_roles': [], 'user_id': u'da155bda1ee74d6c93908e2a37cc4cd4', 'roles': [u'admin'], 'user_domain_id': u'default', 'service_project_id': None, 'service_user_id': None, 'service_user_domain_id': None, 'service_project_domain_id': None, 'is_admin_project': True, 'is_admin': True, 'project_id': u'6e86902b80f944a88327cb5d02f365d8', 'project_domain_id': u'default'}: PolicyNotAuthorized: Policy doesn't allow os_compute_api:os-hide-server-addresses to be performed. {{(pid=6320) authorize /opt/stack/nova/nova/policy.py:168}}
Jun 22 09:51:49 ubuntu nova-api[5615]: INFO nova.osapi_compute.wsgi.server [None req-c2767a4f-c1b5-4d34-be45-1e38c485dc2d demo admin] 10.211.55.6 "GET /v2.1/servers/detail?all_tenants=True&project_id=6e86902b80f944a88327cb5d02f365d8 HTTP/1.1" status: 200 len: 2067 time: 0.5248132
Jun 22 09:51:52 ubuntu nova-api[5615]: DEBUG nova.osapi_compute.wsgi.server [None req-4a8c0b30-41cd-48c8-8897-d99760ab3a7d demo admin] (6320) timed out ('10.211.55.6', 57376): timeout: timed out {{(pid=6320) process_request /usr/local/lib/python2.7/dist-packages/eventlet/wsgi.py:739}}
Jun 22 09:51:54 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._poll_rescued_instances {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._check_instance_build_time {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._poll_rebooting_instances {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager.update_available_resource {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Auditing locally available compute resources for ubuntu (node: ubuntu) {{(pid=5698) update_available_resource /opt/stack/nova/nova/compute/resource_tracker.py:609}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.virt.libvirt.driver [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] skipping disk /dev/disk/by-path/ip-10.211.55.6:3260-iscsi-iqn.2010-10.org.openstack:volume-da516c92-8307-472a-a23c-c2d89653a0bc-lun-1 (vda) as it is a volume {{(pid=5698) _get_instance_disk_info_from_config /opt/stack/nova/nova/virt/libvirt/driver.py:7125}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Hypervisor: free VCPUs: 1 {{(pid=5698) _report_hypervisor_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:730}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Hypervisor/Node resource view: name=ubuntu free_ram=413MB free_disk=26GB free_vcpus=1 pci_devices=[{"dev_id": "pci_0000_00_00_0", "product_id": "29a0", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_29a0", "address": "0000:00:00.0"}, {"dev_id": "pci_0000_00_01_0", "product_id": "2981", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2981", "address": "0000:00:01.0"}, {"dev_id": "pci_0000_01_00_0", "product_id": "4005", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1ab8", "label": "label_1ab8_4005", "address": "0000:01:00.0"}, {"dev_id": "pci_0000_00_03_0", "product_id": "4000", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1ab8", "label": "label_1ab8_4000", "address": "0000:00:03.0"}, {"dev_id": "pci_0000_00_05_0", "product_id": "1000", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1af4", "label": "label_1af4_1000", "address": "0000:00:05.0"}, {"dev_id": "pci_0000_00_0a_0", "product_id": "0022", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1011", "label": "label_1011_0022", "address": "0000:00:0a.0"}, {"dev_id": "pci_0000_00_0e_0", "product_id": "1002", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1af4", "label": "label_1af4_1002", "address": "0000:00:0e.0"}, {"dev_id": "pci_0000_00_1d_0", "product_id": "2658", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2658", "address": "0000:00:1d.0"}, {"dev_id": "pci_0000_00_1d_6", "product_id": "0194", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "1033", "label": "label_1033_0194", "address": "0000:00:1d.6"}, {"dev_id": "pci_0000_00_1d_7", "product_id": "265c", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_265c", "address": "0000:00:1d.7"}, {"dev_id": "pci_0000_00_1e_0", "product_id": "244e", "dev_type": "type-PCI",
Jun 22 09:51:55 ubuntu nova-compute[5698]: "numa_node": null, "vendor_id": "8086", "label": "label_8086_244e", "address": "0000:00:1e.0"}, {"dev_id": "pci_0000_00_1f_0", "product_id": "2810", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2810", "address": "0000:00:1f.0"}, {"dev_id": "pci_0000_00_1f_1", "product_id": "244b", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_244b", "address": "0000:00:1f.1"}, {"dev_id": "pci_0000_00_1f_2", "product_id": "2821", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2821", "address": "0000:00:1f.2"}, {"dev_id": "pci_0000_00_1f_3", "product_id": "283e", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_283e", "address": "0000:00:1f.3"}, {"dev_id": "pci_0000_00_1f_4", "product_id": "2445", "dev_type": "type-PCI", "numa_node": null, "vendor_id": "8086", "label": "label_8086_2445", "address": "0000:00:1f.4"}] {{(pid=5698) _report_hypervisor_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:747}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Lock "compute_resources" acquired by "nova.compute.resource_tracker._update_available_resource" :: waited 0.000s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:270}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.scheduler.client.report [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Refreshing aggregate associations for resource provider 85570fbf-8816-418b-bbba-3c11ae839dcd {{(pid=5698) _ensure_resource_provider /opt/stack/nova/nova/scheduler/client/report.py:438}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.scheduler.client.report [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Instance cf049917-87e9-49e8-9dbd-9c1df24fe411 allocations are unchanged: MEMORY_MB=512,VCPU=1 {{(pid=5698) _allocate_for_instance /opt/stack/nova/nova/scheduler/client/report.py:836}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Total usable vcpus: 2, total allocated vcpus: 1 {{(pid=5698) _report_final_resource_view /opt/stack/nova/nova/compute/resource_tracker.py:763}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: INFO nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Final resource view: name=ubuntu phys_ram=4927MB used_ram=1024MB phys_disk=61GB used_disk=1GB total_vcpus=2 used_vcpus=1 pci_stats=[]
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.scheduler.client.report [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Refreshing aggregate associations for resource provider 85570fbf-8816-418b-bbba-3c11ae839dcd {{(pid=5698) _ensure_resource_provider /opt/stack/nova/nova/scheduler/client/report.py:438}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG nova.compute.resource_tracker [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Compute_service record updated for ubuntu:ubuntu {{(pid=5698) _update_available_resource /opt/stack/nova/nova/compute/resource_tracker.py:701}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Lock "compute_resources" released by "nova.compute.resource_tracker._update_available_resource" :: held 0.496s {{(pid=5698) inner /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:282}}
Jun 22 09:51:55 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._poll_unconfirmed_resizes {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:51:56 ubuntu nova-compute[5698]: DEBUG oslo_service.periodic_task [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Running periodic task ComputeManager._heal_instance_info_cache {{(pid=5698) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
Jun 22 09:51:56 ubuntu nova-compute[5698]: DEBUG nova.compute.manager [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Starting heal instance info cache {{(pid=5698) _heal_instance_info_cache /opt/stack/nova/nova/compute/manager.py:5870}}
Jun 22 09:51:56 ubuntu nova-compute[5698]: DEBUG nova.compute.manager [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Rebuilding the list of instances to heal {{(pid=5698) _heal_instance_info_cache /opt/stack/nova/nova/compute/manager.py:5874}}
Jun 22 09:51:56 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Acquired semaphore "refresh_cache-cf049917-87e9-49e8-9dbd-9c1df24fe411" {{(pid=5698) lock /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:212}}
Jun 22 09:51:56 ubuntu nova-compute[5698]: DEBUG nova.network.neutronv2.api [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] _get_instance_nw_info() {{(pid=5698) _get_instance_nw_info /opt/stack/nova/nova/network/neutronv2/api.py:1284}}
Jun 22 09:51:56 ubuntu nova-compute[5698]: DEBUG nova.objects.instance [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Lazy-loading 'info_cache' on Instance uuid cf049917-87e9-49e8-9dbd-9c1df24fe411 {{(pid=5698) obj_load_attr /opt/stack/nova/nova/objects/instance.py:1039}}
Jun 22 09:51:57 ubuntu nova-compute[5698]: DEBUG nova.network.base_api [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Updating instance_info_cache with network_info: [{"profile": {}, "ovs_interfaceid": "725a32c0-27e1-46e7-83ed-49e5997d15c1", "preserve_on_delete": false, "network": {"bridge": "br-int", "subnets": [{"ips": [{"meta": {}, "version": 4, "type": "fixed", "floating_ips": [], "address": "10.0.0.10"}], "version": 4, "meta": {"dhcp_server": "10.0.0.2"}, "dns": [], "routes": [], "cidr": "10.0.0.0/26", "gateway": {"meta": {}, "version": 4, "type": "gateway", "address": "10.0.0.1"}}, {"ips": [{"meta": {}, "version": 6, "type": "fixed", "floating_ips": [], "address": "fda5:ef20:98e0:0:f816:3eff:fe4f:4c77"}], "version": 6, "meta": {"ipv6_address_mode": "slaac", "dhcp_server": "fda5:ef20:98e0:0:f816:3eff:fee5:40b4"}, "dns": [], "routes": [], "cidr": "fda5:ef20:98e0::/64", "gateway": {"meta": {}, "version": 6, "type": "gateway", "address": "fda5:ef20:98e0::1"}}], "meta": {"injected": false, "tenant_id": "6e86902b80f944a88327cb5d02f365d8", "mtu": 1450}, "id": "e45e6b65-30a8-4bbc-be21-f5a91b31d0e5", "label": "private"}, "devname": "tap725a32c0-27", "vnic_type": "normal", "qbh_params": null, "meta": {}, "details": {"port_filter": true, "ovs_hybrid_plug": true}, "address": "fa:16:3e:4f:4c:77", "active": true, "type": "ovs", "id": "725a32c0-27e1-46e7-83ed-49e5997d15c1", "qbg_params": null}] {{(pid=5698) update_instance_cache_with_nw_info /opt/stack/nova/nova/network/base_api.py:43}}
Jun 22 09:51:57 ubuntu nova-compute[5698]: DEBUG oslo_concurrency.lockutils [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] Releasing semaphore "refresh_cache-cf049917-87e9-49e8-9dbd-9c1df24fe411" {{(pid=5698) lock /usr/local/lib/python2.7/dist-packages/oslo_concurrency/lockutils.py:225}}
Jun 22 09:51:57 ubuntu nova-compute[5698]: DEBUG nova.compute.manager [None req-df9630b4-03b1-4a4b-8bc0-56e8ba4998a0 None None] [instance: cf049917-87e9-49e8-9dbd-9c1df24fe411] Updated the network info_cache for instance {{(pid=5698) _heal_instance_info_cache /opt/stack/nova/nova/compute/manager.py:5932}}
Jun 22 09:51:57 ubuntu nova-scheduler[5687]: DEBUG oslo_service.periodic_task [None req-b0b9dd1d-827b-4339-af55-e82847c70790 None None] Running periodic task SchedulerManager._expire_reservations {{(pid=5687) run_periodic_tasks /usr/local/lib/python2.7/dist-packages/oslo_service/periodic_task.py:215}}
